services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_blog_api
    ports:
      - "5432:5432"

  api:
    build:
      context: ./
    image: docker.io/ranjani07/simple_blog_api
    environment:
      POSTGRES_HOST: postgres # Service name for the postgres container
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: simple_blog_api
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"